version: '3.2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api.template-manager.dev
    env_file: .env.sample
    environment:
      - TEMPLATE_MANAGER_MONGO_ADDRESS=mongodb://mongodb_templatemanager:27017
    ports:
      - 9000:9000
  mongo:
    image: mongo:latest
    container_name: mongodb_templatemanager
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27018:27017
  mongo-admin:
    restart: always
    image: mongo-express:latest
    container_name: mongo-admin_templatemanager
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - 8082:8081
volumes:
  mongodb_data:
    external: false
networks:
  default:
    external:
      name: bubble