version: '3.2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api.data-crawler.dev
    env_file: .env.sample
    environment:
      - DF_MONGO_ADDRESS=mongodb://mongodb_datacrawler:27017
    ports:
      - 9003:9000
  mongo:
    image: mongo:latest
    container_name: mongodb_datacrawler
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27019:27017
  mongo-admin:
    restart: always
    image: mongo-express:latest
    container_name: mongo-admin_datacrawler
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - 8084:8081
volumes:
  mongodb_data:
    external: false
networks:
  default:
    external:
      name: bubble